CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT ,
  password TEXT,
  email TEXT UNIQUE
);

CREATE TABLE todoList (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  userID INTEGER REFERENCES user
);
