CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT ,
  password TEXT,
  email TEXT UNIQUE
);

CREATE TABLE todoList (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  class TEXT,
  userID INTEGER REFERENCES user
);

CREATE TABLE tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  checked INTEGER,
  listID INTEGER REFERENCES todoList
);
